// Generated by CoffeeScript 1.10.0
(function() {
  var update;

  update = function() {
    $.ajax({
      url: "/data",
      dataType: "json",
      error: function(jqKHR, text) {
        console.log(text);
        return update();
      },
      success: function(data) {
        var a, ch, i, len, ref, results, tbody, td0, td1, td2, tr, viewers;
        console.log(data);
        tbody = document.getElementById("tbody");
        $(tbody).empty();
        ref = data.channels;
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          ch = ref[i];
          tr = tbody.appendChild(document.createElement("tr"));
          td0 = tr.appendChild(document.createElement("td"));
          td1 = tr.appendChild(document.createElement("td"));
          td2 = tr.appendChild(document.createElement("td"));
          a = td0.appendChild(document.createElement("a"));
          a.innerHTML = ch.channel;
          a.href = ch.url;
          viewers = ch.viewers;
          if (viewers > 0) {
            td1.innerHTML = ch.game;
            results.push(td2.innerHTML = ch.stream);
          } else {
            results.push(void 0);
          }
        }
        return results;
      }
    });
    return setTimeout(update, 120000);
  };

  update();

}).call(this);
